name: React Project
on: [push,workflow_dispatch]
jobs:
  job1:
    runs-on:  ubuntu-latest
    steps:
      - name: action
        uses: actions/checkout@v3
      - name: build
        run: |
          npm ci
          npm run build
  # job2:
  #   runs-on:  ubuntu-latest
  #   steps:
  #     - name: action
  #       uses: actions/checkout@v3
  #     - name: build
  #       run: |
  #         npm ci
  #         npm run build
