name: Environment
on: [push,workflow_dispatch]
env:
 APP_NAME: Demo App
jobs:
  test:
   env:
     PASSWORD: 123
   runs-on: ubuntu-latest
   steps: 
    - name: Output
      run: | 
       echo "app name:${{env.APP_NAME}}"
       echo "password:${{env.PASSWORD}}"
  deploy:
   needs: test
   runs-on: ubuntu-latest
   steps: 
    - name: Output
      run: | 
       echo "app name:${{env.APP_NAME}}"
       echo "password:${{env.PASSWORD}}"