name: multi-job
on: [push,workflow_dispatch]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print first job
        run: echo "first job"
  second-job: 
    runs-on: ubuntu-latest
    steps:
      - name: print secong job
        run: echo "second job"