#pass data between steps

name: set Color
on: push
jobs:
 test:
  runs-on: ubuntu-latest
  steps: 
    - name: Set Color
      id: demo
      run: echo "color=green" >> $GITHUB_OUTPUT
    - name: Set Num
      id: demo2
      run: echo "num=123" >> $GITHUB_OUTPUT
    - name: get Color
      run: |
        echo "The selected Number is ${{steps.demo2.outputs.num}}"
        echo "The selected color is ${{steps.demo.outputs.color}}"