name: React Project
on: push
env:
  APP_NAME: Demo App
jobs:
  test:
    env:
      PASSWORD: 123
    runs-on: ubuntu-latest
    steps:
      - name: action
        uses: actions/checkout@v3
      - name: cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-dep-${{ hashFiles('**/package-lock.json') }}
      - name: Output
        run: |
          echo "app name:${{env.APP_NAME}}"
          echo "password:${{env.PASSWORD}}"
  doploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output
        run: |
          echo "app name:${{env.APP_NAME}}"
          echo "password:${{env.PASSWORD}}"
