name: React Project
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: action
        uses: actions/checkout@v3
      - name: cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{hashFiles('**/package-lock.json'}}
      - name: Install dependencies
        run: npm ci
      - name: building
        run: npm run build
      - name: test passes
        run: echo "working all test passes"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: action
        uses: actions/checkout@v3
      - name: cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-files-${{hashFiles('**/package-lock.json'}}
      - name: Install dependencies
        run: npm ci
      - name: building
        run: npm run build
      - name: test passes
        run: echo "working all test passes"